version: "3"
services:
  api:
    image: node:12.18.4
    environment:
      - PGUSER=user
      - PGHOST=db
      - PGPASSWORD=password
      - PGDATABASE=authapp
      - PGPORT=5432
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./api
        target: /code
    working_dir: /code
    command: bash -c "npm install && npm run dev"
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./db:/docker-entrypoint-initdb.d/:ro"
    environment:
      - POSTGRES_DB=authapp
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
volumes:
  dbdata:
